plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
}

base { archivesName = 'voice-music-fabric' }

loom {
    splitEnvironmentSourceSets()
    mods { voicemusic { sourceSet sourceSets.main } }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}"
    modRuntimeOnly "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}:fabric-stub"
    implementation project(':core')
    include project(':core')
    include("dev.arbjerg:lavaplayer:${lavaplayer_version}") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    include "dev.lavalink.youtube:v2:${youtube_source_version}"
    include 'com.google.code.gson:gson:2.13.2'
    modRuntimeOnly "maven.modrinth:simple-voice-chat:fabric-2.6.23+26.3"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', minecraft_version
    inputs.property 'loader_version', fabric_loader_version
    filesMatching('fabric.mod.json') {
        expand version: project.version, minecraft_version: minecraft_version,
                loader_version: fabric_loader_version, voicechat_api_version: voicechat_api_version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

java { toolchain.languageVersion = JavaLanguageVersion.of(25); withSourcesJar() }
