org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false
project_version=0.1.0-SNAPSHOT
minecraft_version=26.3
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3
voicechat_api_version=2.6.24
lavaplayer_version=2.2.7
youtube_source_version=1.18.2
